default-profile: dev
profiles:
  dev:
    provider-name: SNOWFLAKE
    connection:
      snowflake:
        connection-string: jdbc:snowflake://${var.account}.snowflakecomputing.com:443
        connection-properties:
          user: ${var.user}
          password: ${var.personal_access_token}
          sys-admin-role: accountadmin
          security-admin-role: accountadmin
