name: deploy-maven
on:
  workflow_call:
    inputs:
      deploy:
        type: boolean
        required: true
      release:
        type: boolean
        required: true
      version:
        type: string
        required: true
      java-version:
        type: string
        required: true
      java-distribution:
        type: string
        required: true
env:
  DEPLOY: ${{ inputs.deploy }}
  RELEASE: ${{ inputs.release }}
  VERSION: ${{ inputs.version }}

jobs:
  publish:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        if: ${{ inputs.deploy }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{inputs.java-version}}
          distribution: ${{inputs.java-distribution}}
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: maven
      - id: install-secret-key
        name: Install gpg secret key
        if: ${{ inputs.deploy }}
        run: |
          # Install gpg secret key
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish package
        if: ${{ inputs.deploy }}
        run:  mvn -Ppublish --batch-mode -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} clean deploy
        env:
          MAVEN_USERNAME: ${{ vars.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}